/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package employee.payroll;

/**
 *
 * @author MasterKhan
 */
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;




public class Addemployee extends javax.swing.JFrame {
Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form Addemployee
     */
    public Addemployee() {
        initComponents();
        this.setLocationRelativeTo(null); //Form in the center of screen
        conn=mysql.ConnectDB();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_phoneno = new javax.swing.JTextField();
        txt_address = new javax.swing.JTextField();
        txt_landmark = new javax.swing.JTextField();
        txt_pc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_salary = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        txt_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_designation = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_status = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cmd_save = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txt_doj = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txt_Back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("First Name:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 115, 194, -1));

        jLabel2.setText("Last Name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 167, 194, -1));

        jLabel3.setText("Date Of Birth:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 217, 194, -1));

        jLabel4.setText("Gender:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 264, 194, -1));

        jLabel5.setText("Phone No:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 360, 194, -1));

        jLabel6.setText("Address:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 397, 194, -1));
        getContentPane().add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 112, 161, -1));
        getContentPane().add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 164, 161, -1));
        getContentPane().add(txt_dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 214, 200, -1));
        getContentPane().add(txt_phoneno, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 357, 200, -1));
        getContentPane().add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 394, 200, -1));
        getContentPane().add(txt_landmark, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 434, 200, -1));
        getContentPane().add(txt_pc, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 469, 200, -1));

        jLabel7.setText("Basic Salary:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 77, 120, -1));
        getContentPane().add(txt_salary, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 74, 200, -1));

        jLabel8.setText("Email:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 306, 79, -1));

        r_male.setText("MALE");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });
        getContentPane().add(r_male, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 260, -1, -1));

        r_female.setText("FEMALE");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });
        getContentPane().add(r_female, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 303, 200, -1));

        jLabel9.setText("Designation:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 115, 120, -1));
        getContentPane().add(txt_designation, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 112, 200, -1));

        jLabel10.setText("Status:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 167, 120, -1));
        getContentPane().add(txt_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 164, 200, -1));

        jButton1.setBackground(new java.awt.Color(255, 0, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/erase-128.png"))); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 455, 157, -1));

        cmd_save.setBackground(new java.awt.Color(0, 102, 255));
        cmd_save.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cmd_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/Save-icon.png"))); // NOI18N
        cmd_save.setText("ADD RECORD");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });
        getContentPane().add(cmd_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 326, 157, -1));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 386, 59, -1));

        jLabel13.setText("LandMark:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 437, -1, -1));

        jLabel14.setText("Pincode:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 472, -1, -1));

        jLabel15.setText("Employee ID:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 77, -1, -1));
        getContentPane().add(txt_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 74, 80, -1));

        jLabel16.setText("Date Hired:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 217, -1, -1));
        getContentPane().add(txt_doj, new org.netbeans.lib.awtextra.AbsoluteConstraints(647, 214, 200, -1));

        jLabel17.setText("Search Employee ID:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 16, -1, -1));

        txt_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_searchMouseClicked(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });
        getContentPane().add(txt_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 13, 200, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 51));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/delete_16x16.gif"))); // NOI18N
        jButton2.setText("DELETE RECORD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 412, 157, -1));

        jButton3.setBackground(new java.awt.Color(0, 255, 51));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/employee/payroll/images/update icon.png"))); // NOI18N
        jButton3.setText("UPDATE RECORD");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 369, -1, -1));

        txt_Back.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Back.setText("BACK\n");
        txt_Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_BackMouseClicked(evt);
            }
        });
        getContentPane().add(txt_Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        gender="Male";
        r_male.setSelected(true);
        r_female.setSelected(false);  // TODO add your handling code here:
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        gender="Female";
        r_female.setSelected(true);
        r_male.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_r_femaleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txt_search.setText("");
        txt_ID.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_phoneno.setText("");
        txt_dob.setText("");
        txt_email.setText("");
        txt_address.setText("");
        txt_status.setText("");
        txt_salary.setText("");
        txt_landmark.setText("");
        txt_pc.setText("");
        txt_designation.setText("");
        txt_doj.setText("");
        r_female.setSelected(false);
        r_male.setSelected(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to add record?","Add Record",JOptionPane.YES_NO_OPTION);
        if(p==0){

            try {
                String sql ="insert into staff_info " 
                        + "(ID,first_name,last_name,Dob,gender,"
                        + "Email,phoneno,Address,Landmark,"
                        + "Pincode,Salary,Designation,"
                        + "Status,Date_hired) values (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ";

                pst=conn.prepareStatement(sql);
                pst.setString(1,txt_ID.getText());
                pst.setString(2,txt_firstname.getText());
                pst.setString(3,txt_lastname.getText());
                pst.setString(4,txt_dob.getText());
                pst.setString(5,gender);
                pst.setString(6,txt_email.getText());
                pst.setString(7,txt_phoneno.getText());
                pst.setString(8,txt_address.getText());
                pst.setString(9,txt_landmark.getText());
                pst.setString(10,txt_pc.getText());
                pst.setString(11,txt_salary.getText());
                pst.setString(12,txt_designation.getText());
                pst.setString(13,txt_status.getText());
                pst.setString(14,txt_doj.getText()); 
                pst.execute();
                JOptionPane.showMessageDialog(null,"Data is saved successfully");

            }
            catch (HeadlessException | SQLException e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
            try {

                String sq ="select * from staff_info where (ID) NOT IN (select ID from employee)";
                pst=conn.prepareStatement(sq);
                rs=pst.executeQuery();

                while(rs.next()){

                    String add1 =rs.getString("ID");
                    String add2 =rs.getString("First_name");
                    String add3 =rs.getString("Last_name");
                   

                    String sql ="insert into Employee (Id,Username,Password) values ('"+add1+"','"+add2+"','"+add3+"') ";
                    pst=conn.prepareStatement(sql);

                    pst.execute();
                    JOptionPane.showMessageDialog(null,"User account has been created successfully: " +" Username:  "+add2+ " Password:  "+add3);
                }

            }catch (HeadlessException | SQLException e)

            {
                JOptionPane.showMessageDialog(null,e);
            }
        
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                 catch(SQLException e){
                   JOptionPane.showMessageDialog(null,e);
                }
            } 
        }        
    }//GEN-LAST:event_cmd_saveActionPerformed

    private void txt_searchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_searchMouseClicked
   
    }//GEN-LAST:event_txt_searchMouseClicked

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
       try{

            String sqc =("select * from staff_info where ID=?");

            pst=conn.prepareStatement(sqc);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            
            if(rs.next()){
            
                String add1 =rs.getString("ID");
                txt_ID.setText(add1);

                String add2 =rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3 =rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4 =rs.getString("Dob");
                txt_dob.setText(add4);
                
                String add5 =rs.getString("Gender");
                System.out.println("add5"+add5);
                if(add5.equalsIgnoreCase("Male"))
                {
                  
                        r_male.setSelected(true);
                        r_female.setSelected(false);
                }
                else
                {
                   
                   r_female.setSelected(true);
                   r_male.setSelected(false); 
                }
                
                String add6 =rs.getString("Email");
                txt_email.setText(add6);

                String add7 =rs.getString("phoneno");
                txt_phoneno.setText(add7);

                String add8 =rs.getString("Address");
                txt_address.setText(add8);

                String add9 =rs.getString("Landmark");
                txt_landmark.setText(add9);
                
                String add10 =rs.getString("Pincode");
                txt_pc.setText(add10);

                String add11 =rs.getString("Salary");
                txt_salary.setText(add11);
                
                String add12 =rs.getString("Designation");
                txt_designation.setText(add12);
                
                String add13 =rs.getString("Status");
                txt_status.setText(add13);
                
                String add14 =rs.getString("Date_hired");
                txt_doj.setText(add14);
            }       
        }catch(SQLException e){
          
        }
        finally {

            try{

                rs.close();
                pst.close();

            }
            catch(SQLException e){

            }
         }  // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the record?","Delete Record",JOptionPane.YES_NO_OPTION);
        if(x==0){
        try{
                String sql ="delete from staff_info where id=? ";
                pst=conn.prepareStatement(sql);
                pst.setString(1, txt_ID.getText());
                pst.execute();
      
                JOptionPane.showMessageDialog(null,"Record Deleted");

        }catch(HeadlessException | SQLException e){

                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){

                }
            }
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int x = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(x==0){
        try{
                String value1 = txt_ID.getText();
                String value2 = txt_firstname.getText();
                String value3 = txt_lastname.getText();
                String value4 = txt_dob.getText();
                String value5 = txt_email.getText();
                String value6 = txt_phoneno.getText();
                String value7 = txt_address.getText();
                String value8 = txt_landmark.getText();
                String value9 = txt_pc.getText();
                String value10 = txt_salary.getText();
                String value11 = txt_designation.getText();
                String value12 = txt_status.getText();
                String value13 = txt_doj.getText();

                String sql= "update staff_info set id='"+value1+"',First_name='"+value2+"',Last_name='"+value3+"', "
                        + "Dob='"+value4+"',Email='"+value5+"',phoneno='"+value6+"',"
                        + "Address='"+value7+"',Landmark='"+value8+"', Pincode = '"+value9+"', "
                        + "Salary= '"+value10+"', Designation='"+value11+"', "
                        + "Status='"+value12+"', Date_hired ='"+value13+"' where id='"+value1+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(null, e);
            }finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(SQLException e){

                }
        } 
        } // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_BackMouseClicked
                new MainMenu().setVisible(true);
                this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BackMouseClicked

 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addemployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Addemployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_save;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JLabel txt_Back;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_designation;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_doj;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_landmark;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_pc;
    private javax.swing.JTextField txt_phoneno;
    private javax.swing.JTextField txt_salary;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_status;
    // End of variables declaration//GEN-END:variables
    private String gender;


}
